import { Geist, Geist_Mono, Anton, Manrope } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const anton = Anton({
  variable:"--font-anton",
  weight: "400",
  subsets: ["latin"],
})

const manrope = Manrope ({
  variable:"--font-manrope",
  weight:["400","500","700"],
  subsets: ["latin"]
})

export const metadata = {
  title: "LES PETITS PLATS",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} ${anton.variable} ${manrope.variable}`}>
        {children}
      </body>
    </html>
  );
}
